### ISSUE TITLE
Relicense to a free license

### ISSUE THREAD

**Issue by ethanc8** [JJTech0130/pypush#106]
Hi,

The "Server Side Public License" is not known to be a license that is actually free/open source -- it's not known that it complies with the Four Freedoms, the Open Source Definition, or the Debian Free Software Guidelines. Although it's possible that the SSPL is actually free and open source, the SSPL's vagueness about how "viral" it is and its extreme copyleft has raised concern amongst open source and free software advocates. Additionally, it's not compatible with the GPL, meaning that pypush can't use any GPL libraries, nor can GPL-licensed projects incorporate pypush. Since pypush is being rewritten, would it be possible to relicense pypush under a well-known license, such as Apache-2.0, LGPL, GPL, or AGPL?

Thanks!

**Comment by topiga** [comment]
From the README :
 > This project has been purchased by [Beeper](https://github.com/beeper), please contact them with any questions about licensing.

I think this still is the case.
