### ISSUE TITLE
wont run demo.py  'type' object is not subscriptable

### ISSUE THREAD

**Issue by JOHNFFFEE** [JJTech0130/pypush#40]
installed all requirements 

ran the command , python37 demo.py

error 

Traceback (most recent call last):
  File "demo.py", line 13, in <module>
    import apns
  File "F:\Users\x\Documents\imessage api\pypush-main\apns.py", line 17, in <module>
    import albert
  File "F:\Users\x\Documents\imessage api\pypush-main\albert.py", line 48, in <module>
    def generate_push_cert() -> tuple[str, str]:
TypeError: 'type' object is not subscriptable

**Comment by JJTech0130** [comment]
This is known behavior, probably should be documented better but 3.10 (or maybe 3.9 now) is the minimum version of Python supported at the moment. Please join the Discord for more support.

**Comment by JOHNFFFEE** [comment]
thank for the quick response , i will installed the new version and try .

**Comment by biemster** [comment]
@JOHNFFFEE You could also delete all the type[...] stuff and other type hinting like I did at one point, then it runs fine with older pythons. (I ran it on 3.8)
It's not that much, probably about 15 minutes work. (but maybe installing a newer version is quicker?)
