### ISSUE TITLE
search_party_token always null

### ISSUE THREAD

**Issue by ErfanDL** [JJTech0130/pypush#44]
after run the bellow code show `Logged in!` message

~/pypush$ python3 ./examples/openhaystack.py

but show this error:
`Error fetching locations (ratelimit?):  401`

in the openhaystack.json
`"search_party_token": null,`

**Comment by JJTech0130** [comment]
Sorry for taking so long to reply: this sounds like an issue with the log in request, probably there is some error being returned that we do not handle. Could you contact me on Discord? I can help you work through debugging it easier there.
I'll take a look at the error handling later, in any case we should be printing something more descriptive than 401

**Comment by ErfanDL** [comment]
> Sorry for taking so long to reply: this sounds like an issue with the log in request, probably there is some error being returned that we do not handle. Could you contact me on Discord? I can help you work through debugging it easier there. I'll take a look at the error handling later, in any case we should be printing something more descriptive than 401

thanks for reply. I don't have access to Discord right now. A question: Do I have to log in to iCloud with an Apple device for it to work?
