### ISSUE TITLE
Verify TLS certificates

### ISSUE THREAD

**Issue by JJTech0130** [JJTech0130/pypush#5]
Apple's certificates are self-signed, so we currently just don't verify them. Eventually we would like to verify them properly.

**Comment by dd-dreams** [comment]
You mean these [ones](https://github.com/search?q=repo%3Abeeper%2Fpypush%20verify%3DFalse&type=code)?

**Comment by JJTech0130** [comment]
Yep!

**Comment by dd-dreams** [comment]
Well, lemme work on it I'll PR real quick.

**Comment by dd-dreams** [comment]
Well, one domain that causes some trouble, is `init-p01st.push.apple.com`.
The problem is, the hostname is not in the certificate hostnames:
```
$ openssl x509 -in init-p01st.push.apple.com.pem -noout -subject
subject=C = US, ST = Massachusetts, L = Cambridge, O = "Akamai Technologies, Inc.", CN = a248.e.akamai.net
```
Which of-course doesn't match the hostname. Hence, I don't think there is an option to actually verify the connection, as the certificate is just wrong.

**Comment by TheTechRobo** [comment]
You could still technically verify it, since it is a valid certificate (just for a different hostname), but probably not with Requests. Or am I missing something?

**Comment by dd-dreams** [comment]
Well, yes, without requests, it will be in some way possible, maybe using `urllib3`. But currently the program uses `requests` so I don't know if we can use `urllib3`.

**Comment by dd-dreams** [comment]
I can currently push a PR for only specific domains, but there will be a couple with `verify=False`.

**Comment by JJTech0130** [comment]
Honestly, I'm kind of thinking that maybe it's better to leave pypush with verify=False, or at least leave a global "DEBUG" option. It's quite useful for debugging to be able to simply mitm the connection. I don't think anyone is really going to be using pypush in an environment where this is a concern?

**Comment by dd-dreams** [comment]
Well I guess pypush is a demo program, so maybe you're right. But if pypush is going to be used as a base of something better, it's important to make security is at its best.

**Comment by SpaceSaver** [comment]
> Well I guess pypush is a demo program, so maybe you're right. But if pypush is going to be used as a base of something better, it's important to make security is at its best.

That is Beeper's plan

**Comment by dd-dreams** [comment]
Then I believe verifying certs should be implemented, at least partially.

**Comment by SpaceSaver** [comment]
> Then I believe verifying certs should be implemented, at least partially.

We should find where Apple devices get the certs.

**Comment by dd-dreams** [comment]
They're already been found. Apple probably verifies the certificates without hostname checks or in another way.

**Comment by TaeHagen** [comment]
Beeper is rewriting pypush in GO, so they can do that there.

If you want to pin the certs, I've already done that in rustpush, look in https://github.com/TaeHagen/rustpush/tree/master/certs/root. All the certs you will need are there.

For the APNs connection, you have to validate the cert against a different hostname (without the number prefix). I do that in rust, not sure how the API's work in python.

**Comment by dd-dreams** [comment]
Then why are commits still being pushed?

**Comment by JJTech0130** [comment]
Merely my own personal project, not on paid time for Beeper. (and occasionally because it's easier to experiment with new features in python)

**Comment by JJTech0130** [comment]
I think I'm going to just close this issue. Not pinning certificates actually makes it much easier for development, and this isn't meant to be used in production. Will be revisited if/when this ever gets pushed to pypi.
