### ISSUE TITLE
Send madrid 130 messages to indicate there is updated registration information

### ISSUE THREAD

**Issue by JJTech0130** [JJTech0130/pypush#50]
Messages with type `130` are sent to devices to notify them that there is updated registration information for them to look up.
This is for both:
+ Other accounts, so that they know to send messages to the newly added device
+ Devices on your own account, so that they can forward to other people that they know about

This would also work around a current issue in Beeper's new bridge, where it does not notice that a phone number was linked with pypush, because it only listens for the 130 (that we do not send) and does not see the ids sign in notification sent by Apple (that real iMessage and the old bridge noticed).

**Comment by SpaceSaver** [comment]
Didn't you fix this?
