### ISSUE TITLE
Use of context on `APNSConnection.start` and its limitations

### ISSUE THREAD

**Issue by novitae** [JJTech0130/pypush#53]
Here is some code I did to be able to use PyPush as a library.
```py
    @classmethod
    async def from_save(
        cls,
        fp: Path
    ) -> "StoredAuthorizedUser":
        with open(fp, "r") as read:
            data = json.load(read)
        
        push_creds = apns.PushCredentials(
            private_key=data["push"]["key"],
            cert=data["push"]["cert"],
            token=base64.b64decode(data["push"]["token"])
        )

        user = data["user"]
        async with apns.APNSConnection.start(push_creds) as connection:
            user = ids.IDSUser( push_connection=connection,
                                user_id=user["id"],
                                auth_keypair=ids._helpers.KeyPair(user["auth_key"], user["auth_cert"]),
                                encryption_identity=ids.identity.IDSIdentity(user["signing_key"], user["encryption_key"]),
                                id_cert=None,
                                handles=user["handles"], )
                
            return cls(
                connection=connection,
                user=user,
                certificates=data.get("certs"),
                earliest_expiration=data.get("earliest_expiration")
            )
```
You can see at the end of this method that I am trying to put my connection to my `__init__` method of my class. However, since the connection is in a context, I can't. When we hit return, even inside of a context, the context gets closed. So I can't use the connection outside of the context. If I do it, it will result in the following error, confirming that the connection got closed:

<img width="781" alt="Capture d’écran 2023-11-25 à 22 42 38" src="https://github.com/JJTech0130/pypush/assets/85891169/10de9611-908e-40dd-b83f-ba86fb12a62d">

If you try to do some of the following stuff, it won't work, or due of the limitations of trio, or due to the limitations of context manager.
```py
connection = apns.APNSConnection.start(push_creds)
```
```py
connection = await apns.APNSConnection.start(push_creds)
```
```py
connection = await apns.APNSConnection.start(push_creds).__anext__()
```
I've also tried to return just after the yield (in the following code) to return the connection, to avoid closing it, etc ... And it just freezes the code.
https://github.com/JJTech0130/pypush/blob/bacefed8b8eb78d5d3f295be5304830665464a04/apns.py#L155-L164

What could I do to avoid the automatic closing of my connection / How can I open it with a manual closing ? (All of this using the async version ofc)

**Comment by JJTech0130** [comment]
you cannot do a manual closing because of the way trio is designed, all your code has to be in a with: block with the nursery to keep the background tasks alive and in-scope.
what you can do is use the less sugary API so that you can manage the trio nursery yourself, and put your whole script in a nursery.

**Comment by JJTech0130** [comment]
probably the best way to make this clear is to just have your class have it's own async context manager, that way your users are aware that it needs to keep a connection open the whole time

it makes forgetting .close impossible, which means you can guarantee you do anything you need to do on shutdown
it makes it possible to use the nursery to schedule background notification handlers etc.

**Comment by JJTech0130** [comment]
like what you would do is basically do what start's asynccontextmanager does, except you put the with APNSConnection.start block in there and inside that yield your own class instead of APNSConnection

**Comment by novitae** [comment]
The workaround I did is save push creds into the class attributes, and then open a connection with them each time I need it inside a class's method. Should do the job for now !
