### ISSUE TITLE
Fix `crontab -e` being hidden

### ISSUE THREAD

**Issue by clari7744** [JJTech0130/pypush#60]
`crontab -e` here is hidden because it's on the same line as \`\`\`, so the markdown parser is reading it as the syntax highlight language instead of the codeblock body. https://github.com/JJTech0130/pypush/blob/b81ae39d7fda004b22c781d6abf4b411533736fc/README.md?plain=1#L98-L100
I'd also suggest changing it to
```
$ crontab -e
```
(adding $) for clarity that it's a terminal command and not something that goes in a file, but that's up to you (should be clear to anybody who reads the directions anyways). if you do decide to add that, should also be added to the other commands, but not terribly important.

**Comment by danipoak** [comment]
Fixed this one. Thanks.
