### ISSUE TITLE
Implement receiving app push notifications

### ISSUE THREAD

**Issue by hanoii** [JJTech0130/pypush#61]
I am not an iOS developer myself, but every now and then I have to do some testings, and one of the things it is requested is a real device to test push notifications, I wonder if this approach can be used for that as well?

Thanks!

**Comment by JJTech0130** [comment]
Yes, this can definitely be implemented in the future

**Comment by alexx96ew** [comment]
> Sam nie jestem programistą iOS, ale od czasu do czasu muszę przeprowadzić pewne testy i jedną z rzeczy, o które proszę, jest prawdziwe urządzenie do testowania powiadomień push. Zastanawiam się, czy można zastosować to podejście również do tego?
> 
> Dzięki!

Ł

**Comment by alexx96ew** [comment]
Ok
