### ISSUE TITLE
ModuleNotFoundError: No module named 'rich'

### ISSUE THREAD

**Issue by DennisFaucher** [JJTech0130/pypush#67]
(Apple Silicon. I'll try on x86 Linux)

    git clone https://github.com/JJTech0130/pypush
    pip3 install -r requirements.txt
    python3 ./demo.py

❯❯python3 ./demo.py
Traceback (most recent call last):
  File "/Users/faucherd/Downloads/pypush/./demo.py", line 11, in <module>
    from rich.logging import RichHandler
ModuleNotFoundError: No module named 'rich'

**Comment by DennisFaucher** [comment]
Yeah, worked fine on x86 Linux. My work Mac is pretty locked down though.

**Comment by Kasherpete** [comment]
Something that may help is using `python3 -m pip` instead of `pip3`. Try that. If it doesn't work, it's because you've got a dual Python install, which is a problem I *may* be able to solve in our support channel, but you can probably find a real fix for it elsewhere.

**Comment by CDeLeon94** [comment]
Thanks for that note Kasherpete, that did the trick for me.

**Comment by DennisFaucher** [comment]
python3 -m ensurepip
python3 -m pip install -r requirements.txt

Fixed it on my Apple Silicon Mac with way too many pythons. Thanks for everyone's help.
