### ISSUE TITLE
Basic UI needed

### ISSUE THREAD

**Issue by AKSHATASTHANA** [JJTech0130/pypush#68]
If not complex i think a basic UI will be helpful instead of all going through terminal that's what I think

**Comment by Kasherpete** [comment]
This will be done once we build an API, which will happen once we merge all the branches together. This is all on our "roadmap", so a UI will be done in due time. However I do happen to have a branch in my fork that has a simple API (though it's a little dated) and I started working on a TUI, though not exactly functional atm. You can check that out in the meantime.

**Comment by AKSHATASTHANA** [comment]
right so maybe we collabrative work upon the UI work I guess

**Comment by tulir** [comment]
https://play.google.com/store/apps/details?id=com.beeper.ima is the UI

**Comment by Pinball3D** [comment]
https://github.com/JJTech0130/pypush/pull/73
