### ISSUE TITLE
No exception thrown if X64 slice is not found

### ISSUE THREAD

**Issue by shashtikar** [JJTech0130/pypush#72]
https://github.com/JJTech0130/pypush/blob/main/emulated/nac.py#L35C51-L35C51 mentions that if an X64 slice is not found, an exception has to be thrown, which is not the case. Throw an exception in the code.

**Comment by JJTech0130** [comment]
I mean, theoretically it will crash because the function returns None, which we try to slice with, right?

**Comment by JJTech0130** [comment]
I'm going to close this issue, since honestly nac.py is only going to ever load a single binary (IMDAppleServices), which is guaranteed to have an x64 slice. If/when we need to make it load more binaries, I'll refactor stuff and fix it anyway.
