### ISSUE TITLE
Unable to find the public key of the sender, cannot verify              

### ISSUE THREAD

**Issue by tellok** [JJTech0130/pypush#74]
>>
>> [16:36:07] WARNING  Unable to find the public key of the sender, cannot verify              imessage.py:404
Traceback (most recent call last):
  File "/Volumes/Code/play/pypush/./demo.py", line 158, in <module>
    msg = im.receive()
          ^^^^^^^^^^^^
  File "/Volumes/Code/play/pypush/imessage.py", line 436, in receive
    raise Exception("Failed to verify payload")
Exception: Failed to verify payload

**Comment by Cypheriel** [comment]
Hello. Sorry for the late reply. Can you please provide us with more information about what caused this error?
What were you doing (or trying to do) when this error occurred?

Additionally, could you try following the installation steps outlined in the async branch of pypush? Currently, this is the only functional branch, and it's possible that your issue has already been fixed there.
