### ISSUE TITLE
Apple 2FA not supported?

### ISSUE THREAD

**Issue by Cr4z33** [JJTech0130/pypush#77]
I've got 2FA enabled for my Apple account and when pypush asks for it I get this after entering the (2FA) code:
```
Traceback (most recent call last):
  File "/pypush/./demo.py", line 341, in <module>
    trio.run(main, args)
  File "/usr/local/lib/python3.11/dist-packages/trio/_core/_run.py", line 2251, in run
    raise runner.main_task_outcome.error
  File "/pypush/./demo.py", line 244, in main
    users.append(ids.IDSAppleUser.authenticate(conn, username, password))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pypush/ids/__init__.py", line 65, in authenticate
    user_id, auth_token = profile.get_auth_token(username, password, factor_callback)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pypush/ids/profile.py", line 64, in get_auth_token
    raise Exception(f"Error: {result}")
Exception: Error: {'message': 'SED:3:VEN-PROD:43aa8e34-ba49-40f5-80f5-e414fe93fb55:432f9f65-bbb9-4aae-b54f-86f2f179292c:1702051751:b67a06b0-7d01-4172-84e2-42c1297a2df0:9a29965493c79209a82f585c6d278c60e87216be5b90dc433a78673066c314aa:EM', 'status': 5012}
```

By the way I am using the `sms-forwarding` branch under Debian.

**Comment by Kasherpete** [comment]
Error 5012 signals a bad username or password, or `InvalidNameOrPassword` to be specific.

**Comment by Cr4z33** [comment]
I am 100% sure that I've entered my login details correctly. 😉

**Comment by Cr4z33** [comment]
Forgot to mention that I try getting the 2FA code by going to appleid.apple.com and asking to send me the code by SMS (I have no Apple devices).

Then of course I don't go on on logging in that page and enter the code in the terminal instead.

Correct or wrong method?

**Comment by Kasherpete** [comment]
Just to confirm that this is a numeric 6 digit code without spaces or dashes?

**Comment by Cr4z33** [comment]
Yep correct and I've already used this method succesfully many times for logging into Apple TV+.

By the way it's strange that with Beeper Mini it doesn't ask for the 2FA code when connecting the Apple ID.

**Comment by Kasherpete** [comment]
This is weird, try switching it to a phone call rather than SMS.

**Comment by Cr4z33** [comment]
@Kasherpete what if I opt not to login into Apple?

Will pypush not work then? 🤔

**Comment by Cr4z33** [comment]
Also maybe it's just a coincidence, but having Apple blocked beeper from accessing iMessage they might have ALSO blocked other third-party solutions like pypush?

**Comment by SpaceSaver** [comment]
When they blocked Beeper, it also blocked Pypush.  Currently Pypush is inoperable.

**Comment by Cr4z33** [comment]
@SpaceSaver as I suspected... OK thanks... 🙁
