### ISSUE TITLE
No cert in response

### ISSUE THREAD

**Issue by mike-lloyd03** [JJTech0130/pypush#81]
For the last few days, I've been getting a new error. Any idea what could be the issue or how I could fix this?

```
./reregister
/opt/pypush /opt/pypush
[11:36:31] INFO     Connected to APNs (33-courier.push.apple.com)                                                                                                                                                                  apns.py:191
           DEBUG    Restoring new-style identity...                                                                                                                                                                                demo.py:200
[11:36:33] INFO     Generated validation data                                                                                                                                                                                       nac.py:415
Traceback (most recent call last):
  File "/opt/pypush/demo.py", line 340, in <module>
    trio.run(main, args)
  File "/opt/pypush/.venv/lib/python3.11/site-packages/trio/_core/_run.py", line 2093, in run
    raise runner.main_task_outcome.error
  File "/opt/pypush/demo.py", line 295, in main
    await reregister(conn, users)
  File "/opt/pypush/demo.py", line 125, in reregister
    register(conn, users)
  File "/opt/pypush/demo.py", line 105, in register
    users = ids.register(conn, users, vd, args.client_data or args.reg_notify)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pypush/ids/__init__.py", line 136, in register
    certs = identity.register(
            ^^^^^^^^^^^^^^^^^^
  File "/opt/pypush/ids/identity.py", line 187, in register
    raise Exception(f"No cert in response: {r}")
Exception: No cert in response: {'services': [{'service': 'com.apple.madrid', 'users': [{'user-id': '<REDACTED>', 'message': '<REDACTED', 'status': 6001}, {'uris': [{'uri': '<REDACTED>', 'status': 0}, {'uri': '<REDACTED>', 'status': 0}], 'user-id': '<REDACTED>', 'cert': b'<REDACTED>', 'status': 0}], 'status': 0}], 'status': 0}
```

However it looks like there is a cert field in the response body. I've removed it here for privacy reasons but it's a string of bytes.

I'm on commit `f205e86bdf1a4ea5414a78985721c721039ada97` of the `sms-registration` branch.

**Comment by Kasherpete** [comment]
Apple has broken Pypush for the time being, and a fix is in the works.

**Comment by mike-lloyd03** [comment]
Ah okay thank you. Should I close this then? Is there already another issue I can subscribe to?

And is discord the place to go for announcements like this?

**Comment by Kasherpete** [comment]
Yeah, you can close this as I'm pretty sure this issue comes from the fact Apple broke it. If you have any other issues once it's working again, you can open another issue if needed. And yeah, Discord is the place for announcements like these.

**Comment by maryjeck** [comment]
In the async branch, you can log in to iMessage, but you cannot send or receive messages .

**Comment by mike-lloyd03** [comment]
> 
> In the async branch, you can log in to iMessage, but you cannot send or receive messages .

I just need my number linked. I'm using blue bubbles for sending and receiving. The `async` branch will work for linking?

**Comment by SpaceSaver** [comment]
> > In the async branch, you can log in to iMessage, but you cannot send or receive messages .
> 
> I just need my number linked. I'm using blue bubbles for sending and receiving. The `async` branch will work for linking?

No, Pypush as a whole is broken until Apple's "patch" is countered.

**Comment by Enduto** [comment]
test

**Comment by Enduto** [comment]
test
