### ISSUE TITLE
demo stuck in Waiting for incoming messages

### ISSUE THREAD

**Issue by elminson** [JJTech0130/pypush#83]
```python3 pypush/demo.py 
[03:04:10] INFO     Connected to APNs (16-courier.push.apple.com)                                                                     apns.py:40
[03:04:11] INFO     Waiting for incoming messages...                                                                                  demo.py:94
Type 'help' for help
```
I remove the config.json but same issue (still debugging)

**Comment by Kasherpete** [comment]
Branch `main` is broken right now. Switch to async using `git switch async`.

**Comment by elminson** [comment]
@Kasherpete Thank you!!!!, when this branch will be merged to main?

**Comment by elminson** [comment]
after switch branch to `async is working`

**Comment by Cypheriel** [comment]
> @Kasherpete Thank you!!!!, when this branch will be merged to main?

There is no set time frame. It's something that's being worked on. (There are some conflicts that must be resolved)

**Comment by Kasherpete** [comment]
> @Kasherpete Thank you!!!!, when this branch will be merged to main? 

Ehh, it really depends. It's not that hard to pass the changes on, but we're gonna be merging all the branches together so it *might* be done then. For now `async` is the only branch that works, and don't really have much of a timeframe for the other ones even though it would be easy.

**Comment by elminson** [comment]
Thank you again! let me know if you need any help with anything I will love to contribute to the project.

**Comment by Kasherpete** [comment]
Will do!
