### ISSUE TITLE
No learning documentation

### ISSUE THREAD

**Issue by alfoson** [JJTech0130/pypush#86]
After cloning the project, messages cannot be sent，
<img width="891" alt="image" src="https://github.com/JJTech0130/pypush/assets/60683409/6a438dbb-2b59-40c6-8bd8-ff0d12797f7e">

**Comment by Cypheriel** [comment]
> After cloning the project, messages cannot be sent，
> <img width="891" alt="image" src="https://github.com/JJTech0130/pypush/assets/60683409/6a438dbb-2b59-40c6-8bd8-ff0d12797f7e">
> 

Hello. Currently, the only functional branch of pypush is the async branch. Please follow the installation instructions there. Also, please note that currently pypush only supports Python 3.10 and 3.11.

**Comment by alfoson** [comment]
thx, i will try again

**Comment by alfoson** [comment]
hello, Participant tel:*******  has no identities, this is probably not a real account, can you give me advise
