### ISSUE TITLE
Cat and Mouse?

### ISSUE THREAD

**Issue by fargly** [JJTech0130/pypush#91]
With Beeper so heavily in the news, I suspect Apple has derailed the mechanism this project uses to send and receive messages. I compiled and ran nacserver (JJTech0130/nacserver) on a valid Intel Mac and swapped out the data.plist file on my Linux box. I reran the initialization to get a new config.json but the software no longer appears to function correctly. This is too bad since it was nice to be able to ssh in from wherever I was working and send iMessages.

### Steps to Replicate

1.  Clone nacserver on an Intel Mac
2. Run build.sh
3. Copy data.plist into emulated directory under pypush
4. rm existing config.json
5. Run demo.py with requirements.txt installed
6. No Joy

**Comment by byquanton** [comment]
Which branch of this repo are you using?

**Comment by fargly** [comment]
commit cc907bc66fe6e4772317a71ea8cb02031e26b5c0 (HEAD -> main, origin/main,
origin/HEAD)

Is there a more appropriate branch or commit to be using?

Cheers

-Kurt

**Comment by TaeHagen** [comment]
Try `async` branch, you may have more luck there.
