### ISSUE TITLE
No sending message (WARNING about his is probably not a real account)

### ISSUE THREAD

**Issue by elminson** [JJTech0130/pypush#92]
WARNING  Participant mailto:xxxxxx@gmail.com has no identities, this is probably not a real account          imessage.py:566
           WARNING  Participant tel:+xxxxxxxxxxxxxx has no identities, this is probably not a real account                   imessage.py:566
In in Async branch and tested. 

I know we are having issues but wanna keep tracking of what I experience

**Comment by Kasherpete** [comment]
This is a known issue and has been an issue for quite some time before Apple's involvement. However @SpaceSaver mentioned in #90 that it *might* have been worsened since then.

**Comment by elminson** [comment]
thank you @Kasherpete I will generate a data.plist (or try to )

**Comment by jzhr** [comment]
instead of generating a new data.plist, using https://github.com/beeper/mac-registration-provider for validation data seems to have worked for me

**Comment by elminson** [comment]
> instead of generating a new data.plist, using https://github.com/beeper/mac-registration-provider for validation data seems to have worked for me

I try @jzhr but say is invalid, can you tell me how to do it? what mac do you have, OS version?

**Comment by Kasherpete** [comment]
> I try @jzhr but say is invalid, can you tell me how to do it? what mac do you have, OS version?

Ah if you have an invalid OS version it won't work. (Also look at Beeper's GitHub, and find the phone registration provider, that's works on an iPhone). More versions will be supported soon.

However like I said before you will most likely not be able to fix this issue, as we don't have any working solution in the code. Check out #90, hopefully that will give you more insight on where this issue stands.

**Comment by jzhr** [comment]
> > instead of generating a new data.plist, using https://github.com/beeper/mac-registration-provider for validation data seems to have worked for me
> 
> I try @jzhr but say is invalid, can you tell me how to do it? what mac do you have, OS version?

@elminson My model is A2442 running Ventura 13.6. #90 linked above has the specific code change

**Comment by SpaceSaver** [comment]
> > instead of generating a new data.plist, using https://github.com/beeper/mac-registration-provider for validation data seems to have worked for me
> 
> I try @jzhr but say is invalid, can you tell me how to do it? what mac do you have, OS version?

So, that won't make a data.plist but will instead use the Mac to generate the validation data which Pypush normally uses the data.plist to generate.  This is unique to each request.
