### ISSUE TITLE
 has been no response.

### ISSUE THREAD

**Issue by NancyDHelms** [JJTech0130/pypush#94]
For the last few days, I tried send imessage ,"is me" is my  content ,But the continuous absence of a response.. and type help not show message, Any idea what could be the issue or how I could fix this?

[02:06:04] INFO     Connected to APNs (5-courier.push.apple.com)                                             apns.py:39
           INFO     Waiting for incoming messages...                                                         demo.py:91
Type 'help' for help
>> help
help (h): show this message
quit (q): quit
filter (f) [recipient]: set the current chat
effect (e): adds an iMessage effect to the next sent message
note: recipient must start with tel: or mailto: and include the country code
handle <handle>: set the current handle (for sending messages)
\: escape commands (will be removed from message)
>> filter +18023061555
>> Filtering to ['tel:+18023061555']
>> is me
>> help
>>

**Comment by SpaceSaver** [comment]
Pypush is broken

**Comment by zhangyu2099** [comment]
you mean pypush cannot be used to  send imessages now？does it be banned by apple .inc ？

**Comment by SpaceSaver** [comment]
> you mean pypush cannot be used to send imessages now？does it be banned by apple .inc ？

Pretty much

**Comment by tg-pgid0** [comment]
Participant mailto:xxxxxx@gmail.com has no identities, this is probably not a real account          imessage.py:1099
Participant tel:+xxxxxxxxxxxxxx has no identities, this is probably not a real account        imessage.py:1099

**Comment by SpaceSaver** [comment]
> Participant [mailto:xxxxxx@gmail.com](mailto:xxxxxx@gmail.com) has no identities, this is probably not a real account imessage.py:1099 Participant tel:+xxxxxxxxxxxxxx has no identities, this is probably not a real account imessage.py:1099

Your Apple ID was banned.

**Comment by tg-pgid0** [comment]
No, I tried to register a new one and the same problem occurred.

**Comment by SpaceSaver** [comment]
> No, I tried to register a new one and the same problem occurred.

Apple limited serial numbers to 10 iMessage registrations.  If u were using the data.plist from the repo, I think it's the same error as banned Apple ID.

**Comment by tg-pgid0** [comment]
I'm using a randomly generated data.plist, not the one from the database.
I have always suspected that pypush is broken.

**Comment by SpaceSaver** [comment]
> I'm using a randomly generated data.plist, not the one from the database. I have always suspected that pypush is broken.

Did you use it for more than 10 accounts (deleting config.json and logging in with the same account I believe counts as another account on the device)?

**Comment by tg-pgid0** [comment]
Yes, I generated multiple config.json for my Apple ID, but they all used different data.plist .

**Comment by SpaceSaver** [comment]
> Yes, I generated multiple config.json for my Apple ID, but they all used different data.plist .

Is the model that you are generating for compatible with Mountain Lion?

**Comment by tg-pgid0** [comment]
Randomly generated based on the Mac ecosystem. After a week of normal use, the above error code started to appear today.

**Comment by SpaceSaver** [comment]
> Randomly generated based on the Mac ecosystem. After a week of normal use, the above error code started to appear today.

Which Mac?

**Comment by tg-pgid0** [comment]
MacBook

**Comment by SpaceSaver** [comment]
> MacBook

Which?

**Comment by SpaceSaver** [comment]
@tg-pgid0 Try `MacBookAir3,2` identifier (may be all lowercase, idk)

**Comment by tg-pgid0** [comment]
https://github.com/beeper/mac-registration-provider

Thank you very much, I will try it and am still looking for useful information.

**Comment by SpaceSaver** [comment]
> https://github.com/beeper/mac-registration-provider
> 
> Thank you very much, I will try it and am still looking for useful information.

This allows you to use real Apple hardware to generate validation data completely bypassing the emulated portion.  Has not been implemented into Pypush yet.
