### ISSUE TITLE
我愿意付费或雇佣寻找能够开发维护的人

### ISSUE THREAD

**Issue by jusrids** [JJTech0130/pypush#97]
如果可以胜任 请报价

**Comment by shuishen49** [comment]
it do not work now!

**Comment by NancyDHelms** [comment]
> 如果可以胜任 请报价

不稳定，还有好长一段路需要走

**Comment by shuishen49** [comment]
> > 如果可以胜任 请报价
> 
> 不稳定，还有好长一段路需要走

so many people use it。 is any one can  send message？
